# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - make out/baremetal-provisioner.service
    - make out/install.sh

builds:
  - id: resource
    binary: pulumi-resource-baremetal
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/unmango/pulumi-baremetal/provider.Version={{.Tag}}
    main: ./cmd/pulumi-resource-baremetal/

  - id: provisioner
    binary: provisioner
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/unmango/pulumi-baremetal/provider/cmd/main.Version={{.Tag}}
    main: ./cmd/provisioner

archives:
  - id: archive
    name_template: pulumi-resource-baremetal-{{ .Tag }}-{{ .Os }}-{{ .Arch }}

release:
  disable: false
  prerelease: auto
  extra_files:
    - glob: dist/provisioner-*
    - glob: out/install.sh
    - glob: out/baremetal-provisioner.service

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
