networks:
  pulumi-baremetal:


x-sdk-test: &sdk-test
  depends_on:
    - provisioner-test
  restart: 'no'
  networks:
    - pulumi-baremetal
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

services:
  provisioner-test:
    build:
      context: .
      dockerfile: provider/cmd/provisioner/Dockerfile
      target: test
      args:
        - VERSION=${VERSION}
    environment:
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
    command: >
      --network tcp4 --address 0.0.0.0:4200 --verbose
    ports:
      - 4200
    networks:
      - pulumi-baremetal

  dotnet-test:
    <<: *sdk-test
    build:
      context: .
      dockerfile: tests/sdk/Dockerfile
      target: dotnet
      args: [ SDK=dotnet ]

  go-test:
    <<: *sdk-test
    build:
      context: .
      dockerfile: tests/sdk/Dockerfile
      args: [ SDK=go ]

  nodejs-test:
    <<: *sdk-test
    build:
      context: .
      dockerfile: tests/sdk/Dockerfile
      args: [ SDK=nodejs ]
      target: nodejs

  python-test:
    <<: *sdk-test
    build:
      context: .
      dockerfile: tests/sdk/Dockerfile
      args: [ SDK=python ]
