# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'TeeOpts',
]

@pulumi.output_type
class TeeOpts(dict):
    def __init__(__self__, *,
                 files: Sequence[str]):
        pulumi.set(__self__, "files", files)

    @property
    @pulumi.getter
    def files(self) -> Sequence[str]:
        return pulumi.get(self, "files")


