// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package baremetal

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
	"github.com/unmango/pulumi-baremetal/sdk/go/baremetal/internal"
)

type Provider struct {
	pulumi.ProviderResourceState

	Address pulumix.Output[string]  `pulumi:"address"`
	CaPem   pulumix.Output[*string] `pulumi:"caPem"`
	CertPem pulumix.Output[*string] `pulumi:"certPem"`
	KeyPem  pulumix.Output[*string] `pulumi:"keyPem"`
	Port    pulumix.Output[*string] `pulumi:"port"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	if args.KeyPem != nil {
		untypedSecretValue := pulumi.ToSecret(args.KeyPem.ToOutput(ctx.Context()).Untyped())
		args.KeyPem = pulumix.MustConvertTyped[*string](untypedSecretValue)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"keyPem",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:baremetal", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	Address string  `pulumi:"address"`
	CaPem   *string `pulumi:"caPem"`
	CertPem *string `pulumi:"certPem"`
	KeyPem  *string `pulumi:"keyPem"`
	Port    *string `pulumi:"port"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	Address pulumix.Input[string]
	CaPem   pulumix.Input[*string]
	CertPem pulumix.Input[*string]
	KeyPem  pulumix.Input[*string]
	Port    pulumix.Input[*string]
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

func (o ProviderOutput) ToOutput(ctx context.Context) pulumix.Output[Provider] {
	return pulumix.Output[Provider]{
		OutputState: o.OutputState,
	}
}

func (o ProviderOutput) Address() pulumix.Output[string] {
	value := pulumix.Apply[Provider](o, func(v Provider) pulumix.Output[string] { return v.Address })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

func (o ProviderOutput) CaPem() pulumix.Output[*string] {
	value := pulumix.Apply[Provider](o, func(v Provider) pulumix.Output[*string] { return v.CaPem })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

func (o ProviderOutput) CertPem() pulumix.Output[*string] {
	value := pulumix.Apply[Provider](o, func(v Provider) pulumix.Output[*string] { return v.CertPem })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

func (o ProviderOutput) KeyPem() pulumix.Output[*string] {
	value := pulumix.Apply[Provider](o, func(v Provider) pulumix.Output[*string] { return v.KeyPem })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

func (o ProviderOutput) Port() pulumix.Output[*string] {
	value := pulumix.Apply[Provider](o, func(v Provider) pulumix.Output[*string] { return v.Port })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

func init() {
	pulumi.RegisterOutputType(ProviderOutput{})
}
