// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cmd

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
	"github.com/unmango/pulumi-baremetal/sdk/go/baremetal/internal"
)

type Mkdir struct {
	pulumi.CustomResourceState

	Args         pulumix.GPtrOutput[MkdirArgsType, MkdirArgsTypeOutput] `pulumi:"args"`
	CreatedFiles pulumix.ArrayOutput[string]                            `pulumi:"createdFiles"`
	CustomDelete pulumix.ArrayOutput[string]                            `pulumi:"customDelete"`
	CustomUpdate pulumix.ArrayOutput[string]                            `pulumi:"customUpdate"`
	ExitCode     pulumix.Output[int]                                    `pulumi:"exitCode"`
	MovedFiles   pulumix.MapOutput[string]                              `pulumi:"movedFiles"`
	Stderr       pulumix.Output[string]                                 `pulumi:"stderr"`
	Stdout       pulumix.Output[string]                                 `pulumi:"stdout"`
	Triggers     pulumix.ArrayOutput[any]                               `pulumi:"triggers"`
}

// NewMkdir registers a new resource with the given unique name, arguments, and options.
func NewMkdir(ctx *pulumi.Context,
	name string, args *MkdirArgs, opts ...pulumi.ResourceOption) (*Mkdir, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Args == nil {
		return nil, errors.New("invalid value for required argument 'Args'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Mkdir
	err := ctx.RegisterResource("baremetal:cmd:Mkdir", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMkdir gets an existing Mkdir resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMkdir(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MkdirState, opts ...pulumi.ResourceOption) (*Mkdir, error) {
	var resource Mkdir
	err := ctx.ReadResource("baremetal:cmd:Mkdir", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Mkdir resources.
type mkdirState struct {
}

type MkdirState struct {
}

func (MkdirState) ElementType() reflect.Type {
	return reflect.TypeOf((*mkdirState)(nil)).Elem()
}

type mkdirArgs struct {
	Args         MkdirArgsType `pulumi:"args"`
	CustomDelete []string      `pulumi:"customDelete"`
	CustomUpdate []string      `pulumi:"customUpdate"`
	Triggers     []interface{} `pulumi:"triggers"`
}

// The set of arguments for constructing a Mkdir resource.
type MkdirArgs struct {
	Args         pulumix.Input[*MkdirArgsTypeArgs]
	CustomDelete pulumix.Input[[]string]
	CustomUpdate pulumix.Input[[]string]
	Triggers     pulumix.Input[[]any]
}

func (MkdirArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*mkdirArgs)(nil)).Elem()
}

type MkdirOutput struct{ *pulumi.OutputState }

func (MkdirOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Mkdir)(nil)).Elem()
}

func (o MkdirOutput) ToMkdirOutput() MkdirOutput {
	return o
}

func (o MkdirOutput) ToMkdirOutputWithContext(ctx context.Context) MkdirOutput {
	return o
}

func (o MkdirOutput) ToOutput(ctx context.Context) pulumix.Output[Mkdir] {
	return pulumix.Output[Mkdir]{
		OutputState: o.OutputState,
	}
}

func (o MkdirOutput) Args() pulumix.GPtrOutput[MkdirArgsType, MkdirArgsTypeOutput] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.GPtrOutput[MkdirArgsType, MkdirArgsTypeOutput] { return v.Args })
	unwrapped := pulumix.Flatten[*MkdirArgsType, pulumix.GPtrOutput[MkdirArgsType, MkdirArgsTypeOutput]](value)
	return pulumix.GPtrOutput[MkdirArgsType, MkdirArgsTypeOutput]{OutputState: unwrapped.OutputState}
}

func (o MkdirOutput) CreatedFiles() pulumix.ArrayOutput[string] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.ArrayOutput[string] { return v.CreatedFiles })
	unwrapped := pulumix.Flatten[[]string, pulumix.ArrayOutput[string]](value)
	return pulumix.ArrayOutput[string]{OutputState: unwrapped.OutputState}
}

func (o MkdirOutput) CustomDelete() pulumix.ArrayOutput[string] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.ArrayOutput[string] { return v.CustomDelete })
	unwrapped := pulumix.Flatten[[]string, pulumix.ArrayOutput[string]](value)
	return pulumix.ArrayOutput[string]{OutputState: unwrapped.OutputState}
}

func (o MkdirOutput) CustomUpdate() pulumix.ArrayOutput[string] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.ArrayOutput[string] { return v.CustomUpdate })
	unwrapped := pulumix.Flatten[[]string, pulumix.ArrayOutput[string]](value)
	return pulumix.ArrayOutput[string]{OutputState: unwrapped.OutputState}
}

func (o MkdirOutput) ExitCode() pulumix.Output[int] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.Output[int] { return v.ExitCode })
	return pulumix.Flatten[int, pulumix.Output[int]](value)
}

func (o MkdirOutput) MovedFiles() pulumix.MapOutput[string] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.MapOutput[string] { return v.MovedFiles })
	unwrapped := pulumix.Flatten[map[string]string, pulumix.MapOutput[string]](value)
	return pulumix.MapOutput[string]{OutputState: unwrapped.OutputState}
}

func (o MkdirOutput) Stderr() pulumix.Output[string] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.Output[string] { return v.Stderr })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

func (o MkdirOutput) Stdout() pulumix.Output[string] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.Output[string] { return v.Stdout })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

func (o MkdirOutput) Triggers() pulumix.ArrayOutput[any] {
	value := pulumix.Apply[Mkdir](o, func(v Mkdir) pulumix.ArrayOutput[any] { return v.Triggers })
	unwrapped := pulumix.Flatten[[]interface{}, pulumix.ArrayOutput[any]](value)
	return pulumix.ArrayOutput[any]{OutputState: unwrapped.OutputState}
}

func init() {
	pulumi.RegisterOutputType(MkdirOutput{})
}
