// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Baremetal.Coreutils.Outputs
{

    [OutputType]
    public sealed class CatArgs
    {
        public readonly bool? E;
        public readonly ImmutableArray<string> Files;
        public readonly bool? Help;
        public readonly bool? Number;
        public readonly bool? NumberNonblank;
        public readonly bool? ShowAll;
        public readonly bool? ShowEnds;
        public readonly bool? ShowNonprinting;
        public readonly bool? ShowTabs;
        public readonly bool? SqueezeBlank;
        public readonly bool? T;
        public readonly bool? Version;

        [OutputConstructor]
        private CatArgs(
            bool? e,

            ImmutableArray<string> files,

            bool? help,

            bool? number,

            bool? numberNonblank,

            bool? showAll,

            bool? showEnds,

            bool? showNonprinting,

            bool? showTabs,

            bool? squeezeBlank,

            bool? t,

            bool? version)
        {
            E = e;
            Files = files;
            Help = help;
            Number = number;
            NumberNonblank = numberNonblank;
            ShowAll = showAll;
            ShowEnds = showEnds;
            ShowNonprinting = showNonprinting;
            ShowTabs = showTabs;
            SqueezeBlank = squeezeBlank;
            T = t;
            Version = version;
        }
    }
}
