// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Baremetal.Coreutils.Outputs
{

    [OutputType]
    public sealed class MktempArgs
    {
        public readonly bool? Directory;
        public readonly bool? DryRun;
        public readonly bool? Help;
        public readonly string? P;
        public readonly bool? Quiet;
        public readonly string? Suffix;
        public readonly bool? T;
        public readonly string? Template;
        public readonly bool? Tmpdir;
        public readonly bool? Version;

        [OutputConstructor]
        private MktempArgs(
            bool? directory,

            bool? dryRun,

            bool? help,

            string? p,

            bool? quiet,

            string? suffix,

            bool? t,

            string? template,

            bool? tmpdir,

            bool? version)
        {
            Directory = directory;
            DryRun = dryRun;
            Help = help;
            P = p;
            Quiet = quiet;
            Suffix = suffix;
            T = t;
            Template = template;
            Tmpdir = tmpdir;
            Version = version;
        }
    }
}
