// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Baremetal.Cmd.Outputs
{

    [OutputType]
    public sealed class WgetArgs
    {
        public readonly string? AppendOutput;
        public readonly bool? Background;
        public readonly string? Base;
        public readonly string? CaCertificateFile;
        public readonly string? CaDirectory;
        public readonly string? Certificate;
        public readonly string? CertificateType;
        public readonly string? Config;
        public readonly bool? Continue;
        public readonly string? CrlFile;
        public readonly int? CutDirs;
        public readonly bool? Debug;
        public readonly string? DirectoryPrefix;
        public readonly ImmutableArray<string> Execute;
        public readonly bool? ForceDirectories;
        public readonly bool? ForceHtml;
        public readonly bool? Help;
        public readonly bool? HttpsOnly;
        public readonly bool? Inet4Only;
        public readonly string? InputFile;
        public readonly bool? KeepSessionCookies;
        public readonly bool? NoClobber;
        public readonly bool? NoDirectories;
        public readonly bool? NoDnsCache;
        public readonly bool? NoVerbose;
        public readonly string? OutputDocument;
        public readonly string? OutputFile;
        public readonly string? Password;
        public readonly string? PrivateKey;
        public readonly string? PrivateKeyType;
        public readonly string? Progress;
        public readonly bool? Quiet;
        public readonly bool? RandomWait;
        public readonly string? ReportSpeed;
        public readonly string? SaveCookies;
        public readonly bool? ShowProgress;
        public readonly string? StartPos;
        public readonly string? Timeout;
        public readonly bool? Timestamping;
        public readonly int? Tries;
        public readonly ImmutableArray<string> Urls;
        public readonly string? User;
        public readonly string? UserAgent;
        public readonly bool? Verbose;
        public readonly string? Version;
        public readonly string? Wait;

        [OutputConstructor]
        private WgetArgs(
            string? appendOutput,

            bool? background,

            string? @base,

            string? caCertificateFile,

            string? caDirectory,

            string? certificate,

            string? certificateType,

            string? config,

            bool? @continue,

            string? crlFile,

            int? cutDirs,

            bool? debug,

            string? directoryPrefix,

            ImmutableArray<string> execute,

            bool? forceDirectories,

            bool? forceHtml,

            bool? help,

            bool? httpsOnly,

            bool? inet4Only,

            string? inputFile,

            bool? keepSessionCookies,

            bool? noClobber,

            bool? noDirectories,

            bool? noDnsCache,

            bool? noVerbose,

            string? outputDocument,

            string? outputFile,

            string? password,

            string? privateKey,

            string? privateKeyType,

            string? progress,

            bool? quiet,

            bool? randomWait,

            string? reportSpeed,

            string? saveCookies,

            bool? showProgress,

            string? startPos,

            string? timeout,

            bool? timestamping,

            int? tries,

            ImmutableArray<string> urls,

            string? user,

            string? userAgent,

            bool? verbose,

            string? version,

            string? wait)
        {
            AppendOutput = appendOutput;
            Background = background;
            Base = @base;
            CaCertificateFile = caCertificateFile;
            CaDirectory = caDirectory;
            Certificate = certificate;
            CertificateType = certificateType;
            Config = config;
            Continue = @continue;
            CrlFile = crlFile;
            CutDirs = cutDirs;
            Debug = debug;
            DirectoryPrefix = directoryPrefix;
            Execute = execute;
            ForceDirectories = forceDirectories;
            ForceHtml = forceHtml;
            Help = help;
            HttpsOnly = httpsOnly;
            Inet4Only = inet4Only;
            InputFile = inputFile;
            KeepSessionCookies = keepSessionCookies;
            NoClobber = noClobber;
            NoDirectories = noDirectories;
            NoDnsCache = noDnsCache;
            NoVerbose = noVerbose;
            OutputDocument = outputDocument;
            OutputFile = outputFile;
            Password = password;
            PrivateKey = privateKey;
            PrivateKeyType = privateKeyType;
            Progress = progress;
            Quiet = quiet;
            RandomWait = randomWait;
            ReportSpeed = reportSpeed;
            SaveCookies = saveCookies;
            ShowProgress = showProgress;
            StartPos = startPos;
            Timeout = timeout;
            Timestamping = timestamping;
            Tries = tries;
            Urls = urls;
            User = user;
            UserAgent = userAgent;
            Verbose = verbose;
            Version = version;
            Wait = wait;
        }
    }
}
