// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package baremetal

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/unmango/pulumi-baremetal/sdk/go/baremetal/internal"
	"github.com/unmango/pulumi-baremetal/sdk/go/baremetal/v1alpha1"
)

// TEE(1)                                                       User Commands                                                      TEE(1)
//
// NAME
//
//	tee - read from standard input and write to standard output and files
//
// SYNOPSIS
//
//	tee [OPTION]... [FILE]...
//
// DESCRIPTION
//
//	    Copy standard input to each FILE, and also to standard output.
//
//	    -a, --append
//	           append to the given FILEs, do not overwrite
//
//	    -i, --ignore-interrupts
//	           ignore interrupt signals
//
//	    -p     operate in a more appropriate MODE with pipes.
//
//	    --output-error[=MODE]
//	           set behavior on write error.  See MODE below
//
//	    --help display this help and exit
//
//	    --version
//	           output version information and exit
//
//	MODE determines behavior with write errors on the outputs:
//	    warn   diagnose errors writing to any output
//
//	    warn-nopipe
//	           diagnose errors writing to any output not a pipe
//
//	    exit   exit on error writing to any output
//
//	    exit-nopipe
//	           exit on error writing to any output not a pipe
//
//	    The default MODE for the -p option is 'warn-nopipe'.  With "nopipe" MODEs, exit immediately if all outputs become broken pipes.
//	    The default operation when --output-error is not specified, is to exit immediately on error writing to a pipe, and diagnose er‐
//	    rors writing to non pipe outputs.
//
// AUTHOR
//
//	Written by Mike Parker, Richard M. Stallman, and David MacKenzie.
//
// REPORTING BUGS
//
//	GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
//	Report any translation bugs to <https://translationproject.org/team/>
//
// COPYRIGHT
//
//	Copyright  ©  2024  Free  Software  Foundation,  Inc.   License  GPLv3+:  GNU  GPL  version  3  or  later  <https://gnu.org/li‐
//	censes/gpl.html>.
//	This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
//
// SEE ALSO
//
//	Full documentation <https://www.gnu.org/software/coreutils/tee>
//	or available locally via: info '(coreutils) tee invocation'
//
// GNU coreutils 9.5                                             March 2024                                                        TEE(1)
type Tee struct {
	pulumi.CustomResourceState

	Create TeeOptsPtrOutput              `pulumi:"create"`
	Stderr pulumi.StringOutput           `pulumi:"stderr"`
	Stdin  pulumi.StringOutput           `pulumi:"stdin"`
	Stdout pulumi.StringOutput           `pulumi:"stdout"`
	Test   v1alpha1.CommandRequestOutput `pulumi:"test"`
}

// NewTee registers a new resource with the given unique name, arguments, and options.
func NewTee(ctx *pulumi.Context,
	name string, args *TeeArgs, opts ...pulumi.ResourceOption) (*Tee, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Stdin == nil {
		return nil, errors.New("invalid value for required argument 'Stdin'")
	}
	if args.Test == nil {
		return nil, errors.New("invalid value for required argument 'Test'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Tee
	err := ctx.RegisterResource("baremetal:index:Tee", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTee gets an existing Tee resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTee(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TeeState, opts ...pulumi.ResourceOption) (*Tee, error) {
	var resource Tee
	err := ctx.ReadResource("baremetal:index:Tee", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Tee resources.
type teeState struct {
}

type TeeState struct {
}

func (TeeState) ElementType() reflect.Type {
	return reflect.TypeOf((*teeState)(nil)).Elem()
}

type teeArgs struct {
	Create *TeeOpts                `pulumi:"create"`
	Stdin  string                  `pulumi:"stdin"`
	Test   v1alpha1.CommandRequest `pulumi:"test"`
}

// The set of arguments for constructing a Tee resource.
type TeeArgs struct {
	Create TeeOptsPtrInput
	Stdin  pulumi.StringInput
	Test   v1alpha1.CommandRequestInput
}

func (TeeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*teeArgs)(nil)).Elem()
}

type TeeInput interface {
	pulumi.Input

	ToTeeOutput() TeeOutput
	ToTeeOutputWithContext(ctx context.Context) TeeOutput
}

func (*Tee) ElementType() reflect.Type {
	return reflect.TypeOf((**Tee)(nil)).Elem()
}

func (i *Tee) ToTeeOutput() TeeOutput {
	return i.ToTeeOutputWithContext(context.Background())
}

func (i *Tee) ToTeeOutputWithContext(ctx context.Context) TeeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TeeOutput)
}

type TeeOutput struct{ *pulumi.OutputState }

func (TeeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Tee)(nil)).Elem()
}

func (o TeeOutput) ToTeeOutput() TeeOutput {
	return o
}

func (o TeeOutput) ToTeeOutputWithContext(ctx context.Context) TeeOutput {
	return o
}

func (o TeeOutput) Create() TeeOptsPtrOutput {
	return o.ApplyT(func(v *Tee) TeeOptsPtrOutput { return v.Create }).(TeeOptsPtrOutput)
}

func (o TeeOutput) Stderr() pulumi.StringOutput {
	return o.ApplyT(func(v *Tee) pulumi.StringOutput { return v.Stderr }).(pulumi.StringOutput)
}

func (o TeeOutput) Stdin() pulumi.StringOutput {
	return o.ApplyT(func(v *Tee) pulumi.StringOutput { return v.Stdin }).(pulumi.StringOutput)
}

func (o TeeOutput) Stdout() pulumi.StringOutput {
	return o.ApplyT(func(v *Tee) pulumi.StringOutput { return v.Stdout }).(pulumi.StringOutput)
}

func (o TeeOutput) Test() v1alpha1.CommandRequestOutput {
	return o.ApplyT(func(v *Tee) v1alpha1.CommandRequestOutput { return v.Test }).(v1alpha1.CommandRequestOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TeeInput)(nil)).Elem(), &Tee{})
	pulumi.RegisterOutputType(TeeOutput{})
}
