// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { KubeadmArgs } from "./kubeadm";
export type Kubeadm = import("./kubeadm").Kubeadm;
export const Kubeadm: typeof import("./kubeadm").Kubeadm = null as any;
utilities.lazyLoad(exports, ["Kubeadm"], () => require("./kubeadm"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "baremetal:kubeadm:Kubeadm":
                return new Kubeadm(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("baremetal", "kubeadm", _module)
