// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace cmd {
    export interface TeeOptsArgs {
        append?: pulumi.Input<boolean>;
        content: pulumi.Input<string>;
        files: pulumi.Input<pulumi.Input<string>[]>;
    }
}
