# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .tee import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import unmango_baremetal.config as __config
    config = __config
else:
    config = _utilities.lazy_import('unmango_baremetal.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "baremetal",
  "mod": "index",
  "fqn": "unmango_baremetal",
  "classes": {
   "baremetal:index:Tee": "Tee"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "baremetal",
  "token": "pulumi:providers:baremetal",
  "fqn": "unmango_baremetal",
  "class": "Provider"
 }
]
"""
)
