name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  provisioner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: provider/go.mod
          cache-dependency-path: provider/go.sum

      - name: Make
        run: make provisioner
