name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - provider
          - sdk
          - tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: provider/go.mod
          cache-dependency-path: provider/go.sum

      - name: golangci-lint ${{ matrix.module }}
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          working-directory: ${{ matrix.module }}

  provisioner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: provider/go.mod
          cache-dependency-path: provider/go.sum

      - name: Make
        run: make provisioner

  provider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: provider/go.mod
          cache-dependency-path: provider/go.sum

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: pulumi/pulumictl

      - name: Install Pulumi
        uses: pulumi/actions@v5
        with:
          pulumi-version-file: .versions/pulumi

      - name: Make
        run: make provider

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-from: gha
          cache-to: gha
          context: .
          file: tests/Dockerfile

      - name: Test
        run: make test_provider
