name: Docker

on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: Override the tag on the image
        required: false
  push:
    branches: [main]
    tags:
      - v*.*.*

jobs:
  provisioner-docker:
    name: Provisioner Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        if: github.event_name == 'push'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: baremetal-provisioner
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ github.token }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: provider/cmd/provisioner/Dockerfile
          tags: ${{ github.event_name == 'push' && steps.meta.outputs.tags || inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
