name: Release

on:
  push:
    tags:
      - v*.*.*
      - '!v*.*.*-**'

env:
  PROVIDER: baremetal
  GITHUB_TOKEN: ${{ github.token }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_REGISTRY_URL: https://registry.npmjs.org
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_FEED_URL: https://api.nuget.org/v3/index.json
  PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  PYPI_USERNAME: __token__

jobs:
  publish_binary:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: provider/go.mod
        cache-dependency-path: provider/go.sum

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        args: -p 3 release
        version: '~> v2'

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        path: dist/resource_linux_amd64_v1/pulumi-resource-baremetal
        name: provider

  publish_sdk:
    name: Publish SDKs
    needs: [publish_binary]
    uses: ./.github/workflows/sdk.yml
    with:
      release: true
