# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'ChmodArgs',
    'MkdirArgs',
    'MktempArgs',
    'MvArgs',
    'RmArgs',
    'TarArgs',
    'TeeArgs',
    'WgetArgs',
]

@pulumi.output_type
class ChmodArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "noPreserveRoot":
            suggest = "no_preserve_root"
        elif key == "octalMode":
            suggest = "octal_mode"
        elif key == "preserveRoot":
            suggest = "preserve_root"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ChmodArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ChmodArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ChmodArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 files: Sequence[str],
                 changes: Optional[bool] = None,
                 help: Optional[bool] = None,
                 mode: Optional[Sequence[str]] = None,
                 no_preserve_root: Optional[bool] = None,
                 octal_mode: Optional[str] = None,
                 preserve_root: Optional[bool] = None,
                 quiet: Optional[bool] = None,
                 recursive: Optional[bool] = None,
                 reference: Optional[str] = None,
                 verbose: Optional[bool] = None,
                 version: Optional[bool] = None):
        pulumi.set(__self__, "files", files)
        if changes is not None:
            pulumi.set(__self__, "changes", changes)
        if help is not None:
            pulumi.set(__self__, "help", help)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if no_preserve_root is not None:
            pulumi.set(__self__, "no_preserve_root", no_preserve_root)
        if octal_mode is not None:
            pulumi.set(__self__, "octal_mode", octal_mode)
        if preserve_root is not None:
            pulumi.set(__self__, "preserve_root", preserve_root)
        if quiet is not None:
            pulumi.set(__self__, "quiet", quiet)
        if recursive is not None:
            pulumi.set(__self__, "recursive", recursive)
        if reference is not None:
            pulumi.set(__self__, "reference", reference)
        if verbose is not None:
            pulumi.set(__self__, "verbose", verbose)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @property
    @pulumi.getter
    def files(self) -> Sequence[str]:
        return pulumi.get(self, "files")

    @property
    @pulumi.getter
    def changes(self) -> Optional[bool]:
        return pulumi.get(self, "changes")

    @property
    @pulumi.getter
    def help(self) -> Optional[bool]:
        return pulumi.get(self, "help")

    @property
    @pulumi.getter
    def mode(self) -> Optional[Sequence[str]]:
        return pulumi.get(self, "mode")

    @property
    @pulumi.getter(name="noPreserveRoot")
    def no_preserve_root(self) -> Optional[bool]:
        return pulumi.get(self, "no_preserve_root")

    @property
    @pulumi.getter(name="octalMode")
    def octal_mode(self) -> Optional[str]:
        return pulumi.get(self, "octal_mode")

    @property
    @pulumi.getter(name="preserveRoot")
    def preserve_root(self) -> Optional[bool]:
        return pulumi.get(self, "preserve_root")

    @property
    @pulumi.getter
    def quiet(self) -> Optional[bool]:
        return pulumi.get(self, "quiet")

    @property
    @pulumi.getter
    def recursive(self) -> Optional[bool]:
        return pulumi.get(self, "recursive")

    @property
    @pulumi.getter
    def reference(self) -> Optional[str]:
        return pulumi.get(self, "reference")

    @property
    @pulumi.getter
    def verbose(self) -> Optional[bool]:
        return pulumi.get(self, "verbose")

    @property
    @pulumi.getter
    def version(self) -> Optional[bool]:
        return pulumi.get(self, "version")


@pulumi.output_type
class MkdirArgs(dict):
    def __init__(__self__, *,
                 directory: Sequence[str],
                 help: Optional[bool] = None,
                 mode: Optional[str] = None,
                 parents: Optional[bool] = None,
                 verbose: Optional[bool] = None,
                 version: Optional[bool] = None):
        pulumi.set(__self__, "directory", directory)
        if help is not None:
            pulumi.set(__self__, "help", help)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if parents is not None:
            pulumi.set(__self__, "parents", parents)
        if verbose is not None:
            pulumi.set(__self__, "verbose", verbose)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @property
    @pulumi.getter
    def directory(self) -> Sequence[str]:
        return pulumi.get(self, "directory")

    @property
    @pulumi.getter
    def help(self) -> Optional[bool]:
        return pulumi.get(self, "help")

    @property
    @pulumi.getter
    def mode(self) -> Optional[str]:
        return pulumi.get(self, "mode")

    @property
    @pulumi.getter
    def parents(self) -> Optional[bool]:
        return pulumi.get(self, "parents")

    @property
    @pulumi.getter
    def verbose(self) -> Optional[bool]:
        return pulumi.get(self, "verbose")

    @property
    @pulumi.getter
    def version(self) -> Optional[bool]:
        return pulumi.get(self, "version")


@pulumi.output_type
class MktempArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "dryRun":
            suggest = "dry_run"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in MktempArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        MktempArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        MktempArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 directory: Optional[bool] = None,
                 dry_run: Optional[bool] = None,
                 help: Optional[bool] = None,
                 p: Optional[str] = None,
                 quiet: Optional[bool] = None,
                 suffix: Optional[str] = None,
                 t: Optional[bool] = None,
                 template: Optional[str] = None,
                 tmpdir: Optional[bool] = None,
                 version: Optional[bool] = None):
        if directory is not None:
            pulumi.set(__self__, "directory", directory)
        if dry_run is not None:
            pulumi.set(__self__, "dry_run", dry_run)
        if help is not None:
            pulumi.set(__self__, "help", help)
        if p is not None:
            pulumi.set(__self__, "p", p)
        if quiet is not None:
            pulumi.set(__self__, "quiet", quiet)
        if suffix is not None:
            pulumi.set(__self__, "suffix", suffix)
        if t is not None:
            pulumi.set(__self__, "t", t)
        if template is not None:
            pulumi.set(__self__, "template", template)
        if tmpdir is not None:
            pulumi.set(__self__, "tmpdir", tmpdir)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @property
    @pulumi.getter
    def directory(self) -> Optional[bool]:
        return pulumi.get(self, "directory")

    @property
    @pulumi.getter(name="dryRun")
    def dry_run(self) -> Optional[bool]:
        return pulumi.get(self, "dry_run")

    @property
    @pulumi.getter
    def help(self) -> Optional[bool]:
        return pulumi.get(self, "help")

    @property
    @pulumi.getter
    def p(self) -> Optional[str]:
        return pulumi.get(self, "p")

    @property
    @pulumi.getter
    def quiet(self) -> Optional[bool]:
        return pulumi.get(self, "quiet")

    @property
    @pulumi.getter
    def suffix(self) -> Optional[str]:
        return pulumi.get(self, "suffix")

    @property
    @pulumi.getter
    def t(self) -> Optional[bool]:
        return pulumi.get(self, "t")

    @property
    @pulumi.getter
    def template(self) -> Optional[str]:
        return pulumi.get(self, "template")

    @property
    @pulumi.getter
    def tmpdir(self) -> Optional[bool]:
        return pulumi.get(self, "tmpdir")

    @property
    @pulumi.getter
    def version(self) -> Optional[bool]:
        return pulumi.get(self, "version")


@pulumi.output_type
class MvArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "noClobber":
            suggest = "no_clobber"
        elif key == "noTargetDirectory":
            suggest = "no_target_directory"
        elif key == "stripTrailingSlashes":
            suggest = "strip_trailing_slashes"
        elif key == "targetDirectory":
            suggest = "target_directory"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in MvArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        MvArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        MvArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 source: Sequence[str],
                 backup: Optional[str] = None,
                 destination: Optional[str] = None,
                 directory: Optional[str] = None,
                 force: Optional[bool] = None,
                 help: Optional[bool] = None,
                 no_clobber: Optional[bool] = None,
                 no_target_directory: Optional[bool] = None,
                 strip_trailing_slashes: Optional[bool] = None,
                 suffix: Optional[str] = None,
                 target_directory: Optional[str] = None,
                 update: Optional[bool] = None,
                 verbose: Optional[bool] = None,
                 version: Optional[bool] = None):
        pulumi.set(__self__, "source", source)
        if backup is not None:
            pulumi.set(__self__, "backup", backup)
        if destination is not None:
            pulumi.set(__self__, "destination", destination)
        if directory is not None:
            pulumi.set(__self__, "directory", directory)
        if force is not None:
            pulumi.set(__self__, "force", force)
        if help is not None:
            pulumi.set(__self__, "help", help)
        if no_clobber is not None:
            pulumi.set(__self__, "no_clobber", no_clobber)
        if no_target_directory is not None:
            pulumi.set(__self__, "no_target_directory", no_target_directory)
        if strip_trailing_slashes is not None:
            pulumi.set(__self__, "strip_trailing_slashes", strip_trailing_slashes)
        if suffix is not None:
            pulumi.set(__self__, "suffix", suffix)
        if target_directory is not None:
            pulumi.set(__self__, "target_directory", target_directory)
        if update is not None:
            pulumi.set(__self__, "update", update)
        if verbose is not None:
            pulumi.set(__self__, "verbose", verbose)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @property
    @pulumi.getter
    def source(self) -> Sequence[str]:
        return pulumi.get(self, "source")

    @property
    @pulumi.getter
    def backup(self) -> Optional[str]:
        return pulumi.get(self, "backup")

    @property
    @pulumi.getter
    def destination(self) -> Optional[str]:
        return pulumi.get(self, "destination")

    @property
    @pulumi.getter
    def directory(self) -> Optional[str]:
        return pulumi.get(self, "directory")

    @property
    @pulumi.getter
    def force(self) -> Optional[bool]:
        return pulumi.get(self, "force")

    @property
    @pulumi.getter
    def help(self) -> Optional[bool]:
        return pulumi.get(self, "help")

    @property
    @pulumi.getter(name="noClobber")
    def no_clobber(self) -> Optional[bool]:
        return pulumi.get(self, "no_clobber")

    @property
    @pulumi.getter(name="noTargetDirectory")
    def no_target_directory(self) -> Optional[bool]:
        return pulumi.get(self, "no_target_directory")

    @property
    @pulumi.getter(name="stripTrailingSlashes")
    def strip_trailing_slashes(self) -> Optional[bool]:
        return pulumi.get(self, "strip_trailing_slashes")

    @property
    @pulumi.getter
    def suffix(self) -> Optional[str]:
        return pulumi.get(self, "suffix")

    @property
    @pulumi.getter(name="targetDirectory")
    def target_directory(self) -> Optional[str]:
        return pulumi.get(self, "target_directory")

    @property
    @pulumi.getter
    def update(self) -> Optional[bool]:
        return pulumi.get(self, "update")

    @property
    @pulumi.getter
    def verbose(self) -> Optional[bool]:
        return pulumi.get(self, "verbose")

    @property
    @pulumi.getter
    def version(self) -> Optional[bool]:
        return pulumi.get(self, "version")


@pulumi.output_type
class RmArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "oneFileSystem":
            suggest = "one_file_system"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RmArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RmArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RmArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 files: Sequence[str],
                 dir: Optional[bool] = None,
                 force: Optional[bool] = None,
                 help: Optional[bool] = None,
                 one_file_system: Optional[bool] = None,
                 recursive: Optional[bool] = None,
                 verbose: Optional[bool] = None):
        pulumi.set(__self__, "files", files)
        if dir is not None:
            pulumi.set(__self__, "dir", dir)
        if force is not None:
            pulumi.set(__self__, "force", force)
        if help is not None:
            pulumi.set(__self__, "help", help)
        if one_file_system is not None:
            pulumi.set(__self__, "one_file_system", one_file_system)
        if recursive is not None:
            pulumi.set(__self__, "recursive", recursive)
        if verbose is not None:
            pulumi.set(__self__, "verbose", verbose)

    @property
    @pulumi.getter
    def files(self) -> Sequence[str]:
        return pulumi.get(self, "files")

    @property
    @pulumi.getter
    def dir(self) -> Optional[bool]:
        return pulumi.get(self, "dir")

    @property
    @pulumi.getter
    def force(self) -> Optional[bool]:
        return pulumi.get(self, "force")

    @property
    @pulumi.getter
    def help(self) -> Optional[bool]:
        return pulumi.get(self, "help")

    @property
    @pulumi.getter(name="oneFileSystem")
    def one_file_system(self) -> Optional[bool]:
        return pulumi.get(self, "one_file_system")

    @property
    @pulumi.getter
    def recursive(self) -> Optional[bool]:
        return pulumi.get(self, "recursive")

    @property
    @pulumi.getter
    def verbose(self) -> Optional[bool]:
        return pulumi.get(self, "verbose")


@pulumi.output_type
class TarArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "excludeFrom":
            suggest = "exclude_from"
        elif key == "excludeVcs":
            suggest = "exclude_vcs"
        elif key == "excludeVcsIgnores":
            suggest = "exclude_vcs_ignores"
        elif key == "ignoreCommandError":
            suggest = "ignore_command_error"
        elif key == "keepDirectorySymlink":
            suggest = "keep_directory_symlink"
        elif key == "keepNewerFiles":
            suggest = "keep_newer_files"
        elif key == "keepOldfiles":
            suggest = "keep_oldfiles"
        elif key == "noAnchored":
            suggest = "no_anchored"
        elif key == "noOverwriteDir":
            suggest = "no_overwrite_dir"
        elif key == "noSeek":
            suggest = "no_seek"
        elif key == "overwriteDir":
            suggest = "overwrite_dir"
        elif key == "removeFiles":
            suggest = "remove_files"
        elif key == "skipOldFiles":
            suggest = "skip_old_files"
        elif key == "stripComponents":
            suggest = "strip_components"
        elif key == "toStdout":
            suggest = "to_stdout"
        elif key == "unlinkFirst":
            suggest = "unlink_first"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in TarArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        TarArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        TarArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 anchored: Optional[bool] = None,
                 append: Optional[bool] = None,
                 args: Optional[Sequence[str]] = None,
                 bzip2: Optional[bool] = None,
                 create: Optional[bool] = None,
                 delete: Optional[bool] = None,
                 diff: Optional[bool] = None,
                 directory: Optional[str] = None,
                 exclude: Optional[str] = None,
                 exclude_from: Optional[str] = None,
                 exclude_vcs: Optional[bool] = None,
                 exclude_vcs_ignores: Optional[bool] = None,
                 extract: Optional[bool] = None,
                 file: Optional[str] = None,
                 gzip: Optional[bool] = None,
                 ignore_command_error: Optional[bool] = None,
                 keep_directory_symlink: Optional[bool] = None,
                 keep_newer_files: Optional[bool] = None,
                 keep_oldfiles: Optional[bool] = None,
                 list: Optional[bool] = None,
                 lzip: Optional[bool] = None,
                 lzma: Optional[bool] = None,
                 lzop: Optional[bool] = None,
                 no_anchored: Optional[bool] = None,
                 no_overwrite_dir: Optional[bool] = None,
                 no_seek: Optional[bool] = None,
                 overwrite: Optional[bool] = None,
                 overwrite_dir: Optional[bool] = None,
                 remove_files: Optional[bool] = None,
                 skip_old_files: Optional[bool] = None,
                 sparse: Optional[bool] = None,
                 strip_components: Optional[int] = None,
                 suffix: Optional[str] = None,
                 to_stdout: Optional[bool] = None,
                 transform: Optional[str] = None,
                 unlink_first: Optional[bool] = None,
                 update: Optional[bool] = None,
                 verbose: Optional[bool] = None,
                 verify: Optional[bool] = None,
                 version: Optional[bool] = None,
                 xz: Optional[bool] = None,
                 zstd: Optional[bool] = None):
        if anchored is not None:
            pulumi.set(__self__, "anchored", anchored)
        if append is not None:
            pulumi.set(__self__, "append", append)
        if args is not None:
            pulumi.set(__self__, "args", args)
        if bzip2 is not None:
            pulumi.set(__self__, "bzip2", bzip2)
        if create is not None:
            pulumi.set(__self__, "create", create)
        if delete is not None:
            pulumi.set(__self__, "delete", delete)
        if diff is not None:
            pulumi.set(__self__, "diff", diff)
        if directory is not None:
            pulumi.set(__self__, "directory", directory)
        if exclude is not None:
            pulumi.set(__self__, "exclude", exclude)
        if exclude_from is not None:
            pulumi.set(__self__, "exclude_from", exclude_from)
        if exclude_vcs is not None:
            pulumi.set(__self__, "exclude_vcs", exclude_vcs)
        if exclude_vcs_ignores is not None:
            pulumi.set(__self__, "exclude_vcs_ignores", exclude_vcs_ignores)
        if extract is not None:
            pulumi.set(__self__, "extract", extract)
        if file is not None:
            pulumi.set(__self__, "file", file)
        if gzip is not None:
            pulumi.set(__self__, "gzip", gzip)
        if ignore_command_error is not None:
            pulumi.set(__self__, "ignore_command_error", ignore_command_error)
        if keep_directory_symlink is not None:
            pulumi.set(__self__, "keep_directory_symlink", keep_directory_symlink)
        if keep_newer_files is not None:
            pulumi.set(__self__, "keep_newer_files", keep_newer_files)
        if keep_oldfiles is not None:
            pulumi.set(__self__, "keep_oldfiles", keep_oldfiles)
        if list is not None:
            pulumi.set(__self__, "list", list)
        if lzip is not None:
            pulumi.set(__self__, "lzip", lzip)
        if lzma is not None:
            pulumi.set(__self__, "lzma", lzma)
        if lzop is not None:
            pulumi.set(__self__, "lzop", lzop)
        if no_anchored is not None:
            pulumi.set(__self__, "no_anchored", no_anchored)
        if no_overwrite_dir is not None:
            pulumi.set(__self__, "no_overwrite_dir", no_overwrite_dir)
        if no_seek is not None:
            pulumi.set(__self__, "no_seek", no_seek)
        if overwrite is not None:
            pulumi.set(__self__, "overwrite", overwrite)
        if overwrite_dir is not None:
            pulumi.set(__self__, "overwrite_dir", overwrite_dir)
        if remove_files is not None:
            pulumi.set(__self__, "remove_files", remove_files)
        if skip_old_files is not None:
            pulumi.set(__self__, "skip_old_files", skip_old_files)
        if sparse is not None:
            pulumi.set(__self__, "sparse", sparse)
        if strip_components is not None:
            pulumi.set(__self__, "strip_components", strip_components)
        if suffix is not None:
            pulumi.set(__self__, "suffix", suffix)
        if to_stdout is not None:
            pulumi.set(__self__, "to_stdout", to_stdout)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)
        if unlink_first is not None:
            pulumi.set(__self__, "unlink_first", unlink_first)
        if update is not None:
            pulumi.set(__self__, "update", update)
        if verbose is not None:
            pulumi.set(__self__, "verbose", verbose)
        if verify is not None:
            pulumi.set(__self__, "verify", verify)
        if version is not None:
            pulumi.set(__self__, "version", version)
        if xz is not None:
            pulumi.set(__self__, "xz", xz)
        if zstd is not None:
            pulumi.set(__self__, "zstd", zstd)

    @property
    @pulumi.getter
    def anchored(self) -> Optional[bool]:
        return pulumi.get(self, "anchored")

    @property
    @pulumi.getter
    def append(self) -> Optional[bool]:
        return pulumi.get(self, "append")

    @property
    @pulumi.getter
    def args(self) -> Optional[Sequence[str]]:
        return pulumi.get(self, "args")

    @property
    @pulumi.getter
    def bzip2(self) -> Optional[bool]:
        return pulumi.get(self, "bzip2")

    @property
    @pulumi.getter
    def create(self) -> Optional[bool]:
        return pulumi.get(self, "create")

    @property
    @pulumi.getter
    def delete(self) -> Optional[bool]:
        return pulumi.get(self, "delete")

    @property
    @pulumi.getter
    def diff(self) -> Optional[bool]:
        return pulumi.get(self, "diff")

    @property
    @pulumi.getter
    def directory(self) -> Optional[str]:
        return pulumi.get(self, "directory")

    @property
    @pulumi.getter
    def exclude(self) -> Optional[str]:
        return pulumi.get(self, "exclude")

    @property
    @pulumi.getter(name="excludeFrom")
    def exclude_from(self) -> Optional[str]:
        return pulumi.get(self, "exclude_from")

    @property
    @pulumi.getter(name="excludeVcs")
    def exclude_vcs(self) -> Optional[bool]:
        return pulumi.get(self, "exclude_vcs")

    @property
    @pulumi.getter(name="excludeVcsIgnores")
    def exclude_vcs_ignores(self) -> Optional[bool]:
        return pulumi.get(self, "exclude_vcs_ignores")

    @property
    @pulumi.getter
    def extract(self) -> Optional[bool]:
        return pulumi.get(self, "extract")

    @property
    @pulumi.getter
    def file(self) -> Optional[str]:
        return pulumi.get(self, "file")

    @property
    @pulumi.getter
    def gzip(self) -> Optional[bool]:
        return pulumi.get(self, "gzip")

    @property
    @pulumi.getter(name="ignoreCommandError")
    def ignore_command_error(self) -> Optional[bool]:
        return pulumi.get(self, "ignore_command_error")

    @property
    @pulumi.getter(name="keepDirectorySymlink")
    def keep_directory_symlink(self) -> Optional[bool]:
        return pulumi.get(self, "keep_directory_symlink")

    @property
    @pulumi.getter(name="keepNewerFiles")
    def keep_newer_files(self) -> Optional[bool]:
        return pulumi.get(self, "keep_newer_files")

    @property
    @pulumi.getter(name="keepOldfiles")
    def keep_oldfiles(self) -> Optional[bool]:
        return pulumi.get(self, "keep_oldfiles")

    @property
    @pulumi.getter
    def list(self) -> Optional[bool]:
        return pulumi.get(self, "list")

    @property
    @pulumi.getter
    def lzip(self) -> Optional[bool]:
        return pulumi.get(self, "lzip")

    @property
    @pulumi.getter
    def lzma(self) -> Optional[bool]:
        return pulumi.get(self, "lzma")

    @property
    @pulumi.getter
    def lzop(self) -> Optional[bool]:
        return pulumi.get(self, "lzop")

    @property
    @pulumi.getter(name="noAnchored")
    def no_anchored(self) -> Optional[bool]:
        return pulumi.get(self, "no_anchored")

    @property
    @pulumi.getter(name="noOverwriteDir")
    def no_overwrite_dir(self) -> Optional[bool]:
        return pulumi.get(self, "no_overwrite_dir")

    @property
    @pulumi.getter(name="noSeek")
    def no_seek(self) -> Optional[bool]:
        return pulumi.get(self, "no_seek")

    @property
    @pulumi.getter
    def overwrite(self) -> Optional[bool]:
        return pulumi.get(self, "overwrite")

    @property
    @pulumi.getter(name="overwriteDir")
    def overwrite_dir(self) -> Optional[bool]:
        return pulumi.get(self, "overwrite_dir")

    @property
    @pulumi.getter(name="removeFiles")
    def remove_files(self) -> Optional[bool]:
        return pulumi.get(self, "remove_files")

    @property
    @pulumi.getter(name="skipOldFiles")
    def skip_old_files(self) -> Optional[bool]:
        return pulumi.get(self, "skip_old_files")

    @property
    @pulumi.getter
    def sparse(self) -> Optional[bool]:
        return pulumi.get(self, "sparse")

    @property
    @pulumi.getter(name="stripComponents")
    def strip_components(self) -> Optional[int]:
        return pulumi.get(self, "strip_components")

    @property
    @pulumi.getter
    def suffix(self) -> Optional[str]:
        return pulumi.get(self, "suffix")

    @property
    @pulumi.getter(name="toStdout")
    def to_stdout(self) -> Optional[bool]:
        return pulumi.get(self, "to_stdout")

    @property
    @pulumi.getter
    def transform(self) -> Optional[str]:
        return pulumi.get(self, "transform")

    @property
    @pulumi.getter(name="unlinkFirst")
    def unlink_first(self) -> Optional[bool]:
        return pulumi.get(self, "unlink_first")

    @property
    @pulumi.getter
    def update(self) -> Optional[bool]:
        return pulumi.get(self, "update")

    @property
    @pulumi.getter
    def verbose(self) -> Optional[bool]:
        return pulumi.get(self, "verbose")

    @property
    @pulumi.getter
    def verify(self) -> Optional[bool]:
        return pulumi.get(self, "verify")

    @property
    @pulumi.getter
    def version(self) -> Optional[bool]:
        return pulumi.get(self, "version")

    @property
    @pulumi.getter
    def xz(self) -> Optional[bool]:
        return pulumi.get(self, "xz")

    @property
    @pulumi.getter
    def zstd(self) -> Optional[bool]:
        return pulumi.get(self, "zstd")


@pulumi.output_type
class TeeArgs(dict):
    def __init__(__self__, *,
                 files: Sequence[str],
                 append: Optional[bool] = None,
                 stdin: Optional[str] = None):
        pulumi.set(__self__, "files", files)
        if append is not None:
            pulumi.set(__self__, "append", append)
        if stdin is not None:
            pulumi.set(__self__, "stdin", stdin)

    @property
    @pulumi.getter
    def files(self) -> Sequence[str]:
        return pulumi.get(self, "files")

    @property
    @pulumi.getter
    def append(self) -> Optional[bool]:
        return pulumi.get(self, "append")

    @property
    @pulumi.getter
    def stdin(self) -> Optional[str]:
        return pulumi.get(self, "stdin")


@pulumi.output_type
class WgetArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "appendOutput":
            suggest = "append_output"
        elif key == "caCertificateFile":
            suggest = "ca_certificate_file"
        elif key == "caDirectory":
            suggest = "ca_directory"
        elif key == "certificateType":
            suggest = "certificate_type"
        elif key == "continue":
            suggest = "continue_"
        elif key == "crlFile":
            suggest = "crl_file"
        elif key == "cutDirs":
            suggest = "cut_dirs"
        elif key == "directoryPrefix":
            suggest = "directory_prefix"
        elif key == "forceDirectories":
            suggest = "force_directories"
        elif key == "forceHtml":
            suggest = "force_html"
        elif key == "httpsOnly":
            suggest = "https_only"
        elif key == "inet4Only":
            suggest = "inet4_only"
        elif key == "inputFile":
            suggest = "input_file"
        elif key == "keepSessionCookies":
            suggest = "keep_session_cookies"
        elif key == "noClobber":
            suggest = "no_clobber"
        elif key == "noDirectories":
            suggest = "no_directories"
        elif key == "noDnsCache":
            suggest = "no_dns_cache"
        elif key == "noVerbose":
            suggest = "no_verbose"
        elif key == "outputDocument":
            suggest = "output_document"
        elif key == "outputFile":
            suggest = "output_file"
        elif key == "privateKey":
            suggest = "private_key"
        elif key == "privateKeyType":
            suggest = "private_key_type"
        elif key == "randomWait":
            suggest = "random_wait"
        elif key == "reportSpeed":
            suggest = "report_speed"
        elif key == "saveCookies":
            suggest = "save_cookies"
        elif key == "showProgress":
            suggest = "show_progress"
        elif key == "startPos":
            suggest = "start_pos"
        elif key == "userAgent":
            suggest = "user_agent"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in WgetArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        WgetArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        WgetArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 urls: Sequence[str],
                 append_output: Optional[str] = None,
                 background: Optional[bool] = None,
                 base: Optional[str] = None,
                 ca_certificate_file: Optional[str] = None,
                 ca_directory: Optional[str] = None,
                 certificate: Optional[str] = None,
                 certificate_type: Optional[str] = None,
                 config: Optional[str] = None,
                 continue_: Optional[bool] = None,
                 crl_file: Optional[str] = None,
                 cut_dirs: Optional[int] = None,
                 debug: Optional[bool] = None,
                 directory_prefix: Optional[str] = None,
                 execute: Optional[Sequence[str]] = None,
                 force_directories: Optional[bool] = None,
                 force_html: Optional[bool] = None,
                 help: Optional[bool] = None,
                 https_only: Optional[bool] = None,
                 inet4_only: Optional[bool] = None,
                 input_file: Optional[str] = None,
                 keep_session_cookies: Optional[bool] = None,
                 no_clobber: Optional[bool] = None,
                 no_directories: Optional[bool] = None,
                 no_dns_cache: Optional[bool] = None,
                 no_verbose: Optional[bool] = None,
                 output_document: Optional[str] = None,
                 output_file: Optional[str] = None,
                 password: Optional[str] = None,
                 private_key: Optional[str] = None,
                 private_key_type: Optional[str] = None,
                 progress: Optional[str] = None,
                 quiet: Optional[bool] = None,
                 random_wait: Optional[bool] = None,
                 report_speed: Optional[str] = None,
                 save_cookies: Optional[str] = None,
                 show_progress: Optional[bool] = None,
                 start_pos: Optional[str] = None,
                 timeout: Optional[str] = None,
                 timestamping: Optional[bool] = None,
                 tries: Optional[int] = None,
                 user: Optional[str] = None,
                 user_agent: Optional[str] = None,
                 verbose: Optional[bool] = None,
                 version: Optional[str] = None,
                 wait: Optional[str] = None):
        pulumi.set(__self__, "urls", urls)
        if append_output is not None:
            pulumi.set(__self__, "append_output", append_output)
        if background is not None:
            pulumi.set(__self__, "background", background)
        if base is not None:
            pulumi.set(__self__, "base", base)
        if ca_certificate_file is not None:
            pulumi.set(__self__, "ca_certificate_file", ca_certificate_file)
        if ca_directory is not None:
            pulumi.set(__self__, "ca_directory", ca_directory)
        if certificate is not None:
            pulumi.set(__self__, "certificate", certificate)
        if certificate_type is not None:
            pulumi.set(__self__, "certificate_type", certificate_type)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if continue_ is not None:
            pulumi.set(__self__, "continue_", continue_)
        if crl_file is not None:
            pulumi.set(__self__, "crl_file", crl_file)
        if cut_dirs is not None:
            pulumi.set(__self__, "cut_dirs", cut_dirs)
        if debug is not None:
            pulumi.set(__self__, "debug", debug)
        if directory_prefix is not None:
            pulumi.set(__self__, "directory_prefix", directory_prefix)
        if execute is not None:
            pulumi.set(__self__, "execute", execute)
        if force_directories is not None:
            pulumi.set(__self__, "force_directories", force_directories)
        if force_html is not None:
            pulumi.set(__self__, "force_html", force_html)
        if help is not None:
            pulumi.set(__self__, "help", help)
        if https_only is not None:
            pulumi.set(__self__, "https_only", https_only)
        if inet4_only is not None:
            pulumi.set(__self__, "inet4_only", inet4_only)
        if input_file is not None:
            pulumi.set(__self__, "input_file", input_file)
        if keep_session_cookies is not None:
            pulumi.set(__self__, "keep_session_cookies", keep_session_cookies)
        if no_clobber is not None:
            pulumi.set(__self__, "no_clobber", no_clobber)
        if no_directories is not None:
            pulumi.set(__self__, "no_directories", no_directories)
        if no_dns_cache is not None:
            pulumi.set(__self__, "no_dns_cache", no_dns_cache)
        if no_verbose is not None:
            pulumi.set(__self__, "no_verbose", no_verbose)
        if output_document is not None:
            pulumi.set(__self__, "output_document", output_document)
        if output_file is not None:
            pulumi.set(__self__, "output_file", output_file)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if private_key is not None:
            pulumi.set(__self__, "private_key", private_key)
        if private_key_type is not None:
            pulumi.set(__self__, "private_key_type", private_key_type)
        if progress is not None:
            pulumi.set(__self__, "progress", progress)
        if quiet is not None:
            pulumi.set(__self__, "quiet", quiet)
        if random_wait is not None:
            pulumi.set(__self__, "random_wait", random_wait)
        if report_speed is not None:
            pulumi.set(__self__, "report_speed", report_speed)
        if save_cookies is not None:
            pulumi.set(__self__, "save_cookies", save_cookies)
        if show_progress is not None:
            pulumi.set(__self__, "show_progress", show_progress)
        if start_pos is not None:
            pulumi.set(__self__, "start_pos", start_pos)
        if timeout is not None:
            pulumi.set(__self__, "timeout", timeout)
        if timestamping is not None:
            pulumi.set(__self__, "timestamping", timestamping)
        if tries is not None:
            pulumi.set(__self__, "tries", tries)
        if user is not None:
            pulumi.set(__self__, "user", user)
        if user_agent is not None:
            pulumi.set(__self__, "user_agent", user_agent)
        if verbose is not None:
            pulumi.set(__self__, "verbose", verbose)
        if version is not None:
            pulumi.set(__self__, "version", version)
        if wait is not None:
            pulumi.set(__self__, "wait", wait)

    @property
    @pulumi.getter
    def urls(self) -> Sequence[str]:
        return pulumi.get(self, "urls")

    @property
    @pulumi.getter(name="appendOutput")
    def append_output(self) -> Optional[str]:
        return pulumi.get(self, "append_output")

    @property
    @pulumi.getter
    def background(self) -> Optional[bool]:
        return pulumi.get(self, "background")

    @property
    @pulumi.getter
    def base(self) -> Optional[str]:
        return pulumi.get(self, "base")

    @property
    @pulumi.getter(name="caCertificateFile")
    def ca_certificate_file(self) -> Optional[str]:
        return pulumi.get(self, "ca_certificate_file")

    @property
    @pulumi.getter(name="caDirectory")
    def ca_directory(self) -> Optional[str]:
        return pulumi.get(self, "ca_directory")

    @property
    @pulumi.getter
    def certificate(self) -> Optional[str]:
        return pulumi.get(self, "certificate")

    @property
    @pulumi.getter(name="certificateType")
    def certificate_type(self) -> Optional[str]:
        return pulumi.get(self, "certificate_type")

    @property
    @pulumi.getter
    def config(self) -> Optional[str]:
        return pulumi.get(self, "config")

    @property
    @pulumi.getter(name="continue")
    def continue_(self) -> Optional[bool]:
        return pulumi.get(self, "continue_")

    @property
    @pulumi.getter(name="crlFile")
    def crl_file(self) -> Optional[str]:
        return pulumi.get(self, "crl_file")

    @property
    @pulumi.getter(name="cutDirs")
    def cut_dirs(self) -> Optional[int]:
        return pulumi.get(self, "cut_dirs")

    @property
    @pulumi.getter
    def debug(self) -> Optional[bool]:
        return pulumi.get(self, "debug")

    @property
    @pulumi.getter(name="directoryPrefix")
    def directory_prefix(self) -> Optional[str]:
        return pulumi.get(self, "directory_prefix")

    @property
    @pulumi.getter
    def execute(self) -> Optional[Sequence[str]]:
        return pulumi.get(self, "execute")

    @property
    @pulumi.getter(name="forceDirectories")
    def force_directories(self) -> Optional[bool]:
        return pulumi.get(self, "force_directories")

    @property
    @pulumi.getter(name="forceHtml")
    def force_html(self) -> Optional[bool]:
        return pulumi.get(self, "force_html")

    @property
    @pulumi.getter
    def help(self) -> Optional[bool]:
        return pulumi.get(self, "help")

    @property
    @pulumi.getter(name="httpsOnly")
    def https_only(self) -> Optional[bool]:
        return pulumi.get(self, "https_only")

    @property
    @pulumi.getter(name="inet4Only")
    def inet4_only(self) -> Optional[bool]:
        return pulumi.get(self, "inet4_only")

    @property
    @pulumi.getter(name="inputFile")
    def input_file(self) -> Optional[str]:
        return pulumi.get(self, "input_file")

    @property
    @pulumi.getter(name="keepSessionCookies")
    def keep_session_cookies(self) -> Optional[bool]:
        return pulumi.get(self, "keep_session_cookies")

    @property
    @pulumi.getter(name="noClobber")
    def no_clobber(self) -> Optional[bool]:
        return pulumi.get(self, "no_clobber")

    @property
    @pulumi.getter(name="noDirectories")
    def no_directories(self) -> Optional[bool]:
        return pulumi.get(self, "no_directories")

    @property
    @pulumi.getter(name="noDnsCache")
    def no_dns_cache(self) -> Optional[bool]:
        return pulumi.get(self, "no_dns_cache")

    @property
    @pulumi.getter(name="noVerbose")
    def no_verbose(self) -> Optional[bool]:
        return pulumi.get(self, "no_verbose")

    @property
    @pulumi.getter(name="outputDocument")
    def output_document(self) -> Optional[str]:
        return pulumi.get(self, "output_document")

    @property
    @pulumi.getter(name="outputFile")
    def output_file(self) -> Optional[str]:
        return pulumi.get(self, "output_file")

    @property
    @pulumi.getter
    def password(self) -> Optional[str]:
        return pulumi.get(self, "password")

    @property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> Optional[str]:
        return pulumi.get(self, "private_key")

    @property
    @pulumi.getter(name="privateKeyType")
    def private_key_type(self) -> Optional[str]:
        return pulumi.get(self, "private_key_type")

    @property
    @pulumi.getter
    def progress(self) -> Optional[str]:
        return pulumi.get(self, "progress")

    @property
    @pulumi.getter
    def quiet(self) -> Optional[bool]:
        return pulumi.get(self, "quiet")

    @property
    @pulumi.getter(name="randomWait")
    def random_wait(self) -> Optional[bool]:
        return pulumi.get(self, "random_wait")

    @property
    @pulumi.getter(name="reportSpeed")
    def report_speed(self) -> Optional[str]:
        return pulumi.get(self, "report_speed")

    @property
    @pulumi.getter(name="saveCookies")
    def save_cookies(self) -> Optional[str]:
        return pulumi.get(self, "save_cookies")

    @property
    @pulumi.getter(name="showProgress")
    def show_progress(self) -> Optional[bool]:
        return pulumi.get(self, "show_progress")

    @property
    @pulumi.getter(name="startPos")
    def start_pos(self) -> Optional[str]:
        return pulumi.get(self, "start_pos")

    @property
    @pulumi.getter
    def timeout(self) -> Optional[str]:
        return pulumi.get(self, "timeout")

    @property
    @pulumi.getter
    def timestamping(self) -> Optional[bool]:
        return pulumi.get(self, "timestamping")

    @property
    @pulumi.getter
    def tries(self) -> Optional[int]:
        return pulumi.get(self, "tries")

    @property
    @pulumi.getter
    def user(self) -> Optional[str]:
        return pulumi.get(self, "user")

    @property
    @pulumi.getter(name="userAgent")
    def user_agent(self) -> Optional[str]:
        return pulumi.get(self, "user_agent")

    @property
    @pulumi.getter
    def verbose(self) -> Optional[bool]:
        return pulumi.get(self, "verbose")

    @property
    @pulumi.getter
    def version(self) -> Optional[str]:
        return pulumi.get(self, "version")

    @property
    @pulumi.getter
    def wait(self) -> Optional[str]:
        return pulumi.get(self, "wait")


